package com.ndming.kabob.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

private val capricornColorLightPrimary                 = Color(0xFF324D62)
private val capricornColorLightOnPrimary               = Color(0xFFFEFEFE)
private val capricornColorLightPrimaryContainer        = Color(0xFFC4D6DD)
private val capricornColorLightOnPrimaryContainer      = Color(0xFF0F2D44)
private val capricornColorLightInversePrimary          = Color(0xFFD9E6F0)
private val capricornColorLightSecondary               = Color(0xFF50606F)
private val capricornColorLightOnSecondary             = Color(0xFFFEFEFE)
private val capricornColorLightSecondaryContainer      = Color(0xFFD2DCE6)
private val capricornColorLightOnSecondaryContainer    = Color(0xFF20303D)
private val capricornColorLightTertiary                = Color(0xFF693E09)
private val capricornColorLightOnTertiary              = Color(0xFFFEFEFE)
private val capricornColorLightTertiaryContainer       = Color(0xFFFEDBC1)
private val capricornColorLightOnTertiaryContainer     = Color(0xFF2E1500)
private val capricornColorLightError                   = Color(0xFFB91A1A)
private val capricornColorLightOnError                 = Color(0xFFFEFEFE)
private val capricornColorLightErrorContainer          = Color(0xFFFED9D5)
private val capricornColorLightOnErrorContainer        = Color(0xFF410002)
private val capricornColorLightBackground              = Color(0xFFFBFBFE)
private val capricornColorLightOnBackground            = Color(0xFF1A1C1E)
private val capricornColorLightSurface                 = Color(0xFFFBFBFE)
private val capricornColorLightSurfaceContainerLow     = Color(0xFFF0F0F3)
private val capricornColorLightSurfaceContainerHighest = Color(0xFFEEF4F5)
private val capricornColorLightOnSurface               = Color(0xFF1A1C1E)
private val capricornColorLightSurfaceVariant          = Color(0xFFE6EEEF)
private val capricornColorLightOnSurfaceVariant        = Color(0xFF41474D)
private val capricornColorLightSurfaceTint             = Color(0xFF748EA3)
private val capricornColorLightInverseSurface          = Color(0xFF32393E)
private val capricornColorLightInverseOnSurface        = Color(0xFFEFEFF2)
private val capricornColorLightOutline                 = Color(0xFF63696F)
private val capricornColorLightOutlineVariant          = Color(0xFFCED5DF)
private val capricornColorLightScrim                   = Color(0xFF485B6A)

val capricornLightScheme = lightColorScheme(
    primary                 = capricornColorLightPrimary,
    onPrimary               = capricornColorLightOnPrimary,
    primaryContainer        = capricornColorLightPrimaryContainer,
    onPrimaryContainer      = capricornColorLightOnPrimaryContainer,
    inversePrimary          = capricornColorLightInversePrimary,
    secondary               = capricornColorLightSecondary,
    onSecondary             = capricornColorLightOnSecondary,
    secondaryContainer      = capricornColorLightSecondaryContainer,
    onSecondaryContainer    = capricornColorLightOnSecondaryContainer,
    tertiary                = capricornColorLightTertiary,
    onTertiary              = capricornColorLightOnTertiary,
    tertiaryContainer       = capricornColorLightTertiaryContainer,
    onTertiaryContainer     = capricornColorLightOnTertiaryContainer,
    error                   = capricornColorLightError,
    onError                 = capricornColorLightOnError,
    errorContainer          = capricornColorLightErrorContainer,
    onErrorContainer        = capricornColorLightOnErrorContainer,
    background              = capricornColorLightBackground,
    onBackground            = capricornColorLightOnBackground,
    surface                 = capricornColorLightSurface,
    surfaceContainerLow     = capricornColorLightSurfaceContainerLow,
    surfaceContainerHighest = capricornColorLightSurfaceContainerHighest,
    onSurface               = capricornColorLightOnSurface,
    surfaceVariant          = capricornColorLightSurfaceVariant,
    onSurfaceVariant        = capricornColorLightOnSurfaceVariant,
    surfaceTint             = capricornColorLightSurfaceTint,
    inverseSurface          = capricornColorLightInverseSurface,
    inverseOnSurface        = capricornColorLightInverseOnSurface,
    outline                 = capricornColorLightOutline,
    outlineVariant          = capricornColorLightOutlineVariant,
    scrim                   = capricornColorLightScrim
)

private val capricornColorDarkPrimary                 = Color(0xFFBCDAF2)
private val capricornColorDarkOnPrimary               = Color(0xFF283E49)
private val capricornColorDarkPrimaryContainer        = Color(0xFF455E6A)
private val capricornColorDarkOnPrimaryContainer      = Color(0xFFD1F0FE)
private val capricornColorDarkInversePrimary          = Color(0xFF172E38)
private val capricornColorDarkSecondary               = Color(0xFFB6C7D8)
private val capricornColorDarkOnSecondary             = Color(0xFF22323F)
private val capricornColorDarkSecondaryContainer      = Color(0xFF394956)
private val capricornColorDarkOnSecondaryContainer    = Color(0xFFD2E4F5)
private val capricornColorDarkTertiary                = Color(0xFFFEB67B)
private val capricornColorDarkOnTertiary              = Color(0xFF4C2700)
private val capricornColorDarkTertiaryContainer       = Color(0xFF6D3A00)
private val capricornColorDarkOnTertiaryContainer     = Color(0xFFFEDBC1)
private val capricornColorDarkError                   = Color(0xFFF8AFA6)
private val capricornColorDarkOnError                 = Color(0xFF670005)
private val capricornColorDarkErrorContainer          = Color(0xFF8C000A)
private val capricornColorDarkOnErrorContainer        = Color(0xFFF5D1CD)
private val capricornColorDarkBackground              = Color(0xFF191B1D)
private val capricornColorDarkOnBackground            = Color(0xFFE1E1E4)
private val capricornColorDarkSurface                 = Color(0xFF1A1C1E)
private val capricornColorDarkSurfaceContainerLow     = Color(0xFF1B2023)
private val capricornColorDarkSurfaceContainerHighest = Color(0xFF1F262C)
private val capricornColorDarkOnSurface               = Color(0xFFE1E1E4)
private val capricornColorDarkSurfaceVariant          = Color(0xFF1F262C)
private val capricornColorDarkOnSurfaceVariant        = Color(0xFFBDC3CA)
private val capricornColorDarkSurfaceTint             = Color(0xFFC2D3E0)
private val capricornColorDarkInverseSurface          = Color(0xFFDAE4EC)
private val capricornColorDarkInverseOnSurface        = Color(0xFF1A1C1E)
private val capricornColorDarkOutline                 = Color(0xFF8A9097)
private val capricornColorDarkOutlineVariant          = Color(0xFF3D4249)
private val capricornColorDarkScrim                   = Color(0xFF485B6A)

val capricornDarkScheme = darkColorScheme(
    primary                 = capricornColorDarkPrimary,
    onPrimary               = capricornColorDarkOnPrimary,
    primaryContainer        = capricornColorDarkPrimaryContainer,
    onPrimaryContainer      = capricornColorDarkOnPrimaryContainer,
    inversePrimary          = capricornColorDarkInversePrimary,
    secondary               = capricornColorDarkSecondary,
    onSecondary             = capricornColorDarkOnSecondary,
    secondaryContainer      = capricornColorDarkSecondaryContainer,
    onSecondaryContainer    = capricornColorDarkOnSecondaryContainer,
    tertiary                = capricornColorDarkTertiary,
    onTertiary              = capricornColorDarkOnTertiary,
    tertiaryContainer       = capricornColorDarkTertiaryContainer,
    onTertiaryContainer     = capricornColorDarkOnTertiaryContainer,
    error                   = capricornColorDarkError,
    onError                 = capricornColorDarkOnError,
    errorContainer          = capricornColorDarkErrorContainer,
    onErrorContainer        = capricornColorDarkOnErrorContainer,
    background              = capricornColorDarkBackground,
    onBackground            = capricornColorDarkOnBackground,
    surface                 = capricornColorDarkSurface,
    surfaceContainerLow     = capricornColorDarkSurfaceContainerLow,
    surfaceContainerHighest = capricornColorDarkSurfaceContainerHighest,
    onSurface               = capricornColorDarkOnSurface,
    surfaceVariant          = capricornColorDarkSurfaceVariant,
    onSurfaceVariant        = capricornColorDarkOnSurfaceVariant,
    surfaceTint             = capricornColorDarkSurfaceTint,
    inverseSurface          = capricornColorDarkInverseSurface,
    inverseOnSurface        = capricornColorDarkInverseOnSurface,
    outline                 = capricornColorDarkOutline,
    outlineVariant          = capricornColorDarkOutlineVariant,
    scrim                   = capricornColorDarkScrim
)